# Compiler and flags
CC = g++
CFLAGS = -I./ConsoleUI  # Include the ConsoleUI folder for headers

# File locations
CONSOLE_SOURCE = ConsoleUI\ConsoleUI.cpp ConsoleUI\AConsoleUI\AConsoleUI.cpp ConsoleUI\ProcessUI\ProcessUI.cpp ConsoleUI\MainMenuUI\MainMenuUI.cpp
SOURCES = main.cpp $(CONSOLE_SOURCE) Config/config.cpp Process/Process.cpp Screen/Screen.cpp CPU/Scheduler.cpp Threads/Threads.cpp 

OBJECTS = $(SOURCES:.cpp=.o)
EXEC = main # Name of the output executable

# Default target to compile and link
$(EXEC): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(EXEC)

# Rule to compile each .cpp file to .o object files
%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@


# Clean up generated OBject files and executable
clean:
	rm -f $(OBJECTS) $(EXEC)