# Compiler and flags
CC = g++
CFLAGS = -I./ConsoleUI  # Include the ConsoleUI folder for headers

# File locations
CONSOLE_SOURCE = ConsoleUI\ConsoleUI.cpp ConsoleUI\AConsoleUI\AConsoleUI.cpp ConsoleUI\ProcessUI\ProcessUI.cpp ConsoleUI\MainMenuUI\MainMenuUI.cpp
PROCESS_SOURCE= Process\Process.cpp Process\Instruction\Instruction.cpp Process\Instruction\Add.cpp Process\Instruction\Declare.cpp Process\Instruction\Print.cpp Process\Instruction\Sub.cpp
SCHEDULER_SOURCE = Scheduler\Scheduler.cpp
SOURCES = main.cpp $(SCHEDULER_SOURCE) $(PROCESS_SOURCE) $(CONSOLE_SOURCE) Config/config.cpp  CPU\CPU.cpp

OBJECTS = $(SOURCES:.cpp=.o)
EXEC = main # Name of the output executable

# Default target to compile and link
$(EXEC): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(EXEC)

# Rule to compile each .cpp file to .o object files
%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@


# Clean up generated OBject files and executable
clean:
	rm -f $(OBJECTS) $(EXEC)